version: "3"
services:

  proxy:
    ports:
      - "${PORT_TRAEFIK-80}:80"
      - "${PORT_TRAEFIK_DASHBOARD-8080}:8080"
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
    labels:
      - traefik.enable=true
      - traefik.http.routers.${STACK_NAME?Variable not set}-traefik-public.http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.services.${STACK_NAME?Variable not set}-traefik-public.loadbalancer.server.port=80

  db:
    ports:
      - "${PORT_DB-5432}:5432"

  api:
    ports:
      - "${PORT_BACKEND-8888}:80"
    volumes:
      - ./api/app:/app
    build:
      context: ./api
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /start-reload.sh
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not set}-api-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`)
      - traefik.http.services.${STACK_NAME?Variable not set}-api.loadbalancer.server.port=80

networks:
  traefik-public:
    external: false
