# Server
SERVER = "http://127.0.0.1:8000"

# Menu
MENU_ASSETS = "assets/gui/icons"

# Player
HELMET_SCALE = 3
BODY_SCALE = 3
LEGS_SCALE = 3
GLOVES_SCALE = 3
BOOTS_SCALE = 3
MAIN_HAND_SCALE = 3
OFF_HAND_SCALE = 3

# Game
CAMERA_SPEED = 0.1
PLAYER_SCALE = 3
CURSOR_SCALE = 0.4
RIGHT_BUTTON_SCALE = 1.5
PORTRAIT_PANEL_SCALE = 2
PORTRAIT_SCALE = 0.18
ICON_SCALE = 1.5
INGAME_WINDOW_SCALE = 1

DAYLIGHT_SPEED = 0.1

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "Mort"
